/** @type {import('tailwindcss').Config} */
/** Colors use CSS vars so dark/light (shop design) can switch at runtime. */
module.exports = {
  content: ["./web/src/**/*.{html,js,svelte}", "./web/templates/**/*.html"],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--c-bg) / <alpha-value>)",
        surface: "rgb(var(--c-bg) / <alpha-value>)",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "surface-bright": "rgb(var(--c-bg) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--c-panel) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-panel-2) / <alpha-value>)",
        "surface-container": "rgb(var(--c-panel) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-elevated) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--c-elevated) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-elevated) / <alpha-value>)",
        "on-surface": "rgb(var(--c-text) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-muted) / <alpha-value>)",
        "on-background": "rgb(var(--c-text) / <alpha-value>)",
        outline: "rgb(var(--c-dim) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-border) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--c-panel-2) / <alpha-value>)",
        "on-primary-container": "rgb(var(--c-muted) / <alpha-value>)",
        secondary: "rgb(var(--c-green) / <alpha-value>)",
        "on-secondary": "rgb(var(--c-on-green) / <alpha-value>)",
        "secondary-container": "rgb(var(--c-green) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--c-on-green) / <alpha-value>)",
        tertiary: "rgb(var(--c-green) / <alpha-value>)",
        "on-tertiary": "rgb(var(--c-on-green) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--c-green) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--c-green) / <alpha-value>)",
        "tertiary-fixed-variant": "rgb(var(--c-green-hover) / <alpha-value>)",
        error: "rgb(var(--c-error) / <alpha-value>)",
        "on-error": "rgb(var(--c-on-error) / <alpha-value>)",
        "error-container": "rgb(var(--c-error-bg) / <alpha-value>)",
        "on-error-container": "rgb(var(--c-error-fg) / <alpha-value>)",
        pending: "rgb(var(--c-pending) / <alpha-value>)",
        closed: "rgb(var(--c-dim) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        "label-md": ["Inter", "ui-sans-serif", "sans-serif"],
        "data-display": ['"JetBrains Mono"', "ui-monospace", "monospace"],
        "headline-lg": ["Inter", "ui-sans-serif", "sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif", "sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif", "sans-serif"],
        "body-md": ["Inter", "ui-sans-serif", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "800" }],
        "data-display": ["18px", { lineHeight: "24px", fontWeight: "700" }],
      },
      spacing: {
        "container-margin": "1rem",
        "section-padding": "1.5rem",
        "inline-gap": "0.5rem",
        "stack-gap": "0.75rem",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
      },
      boxShadow: {
        float: "var(--c-shadow)",
        "2xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
    },
  },
  plugins: [],
};
