/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./web/src/**/*.{html,js,svelte}', './web/templates/**/*.html'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#44474d',
        'on-background': '#191c1e',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        primary: '#0a192f',
        'on-primary': '#ffffff',
        'primary-container': '#0d1c32',
        'on-primary-container': '#76849f',
        secondary: '#0059bb',
        'on-secondary': '#ffffff',
        'secondary-container': '#0070ea',
        'on-secondary-container': '#fefcff',
        tertiary: '#28a745',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#0d9838',
        'tertiary-fixed': '#83fc8e',
        'tertiary-fixed-variant': '#00531a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        pending: '#f59e0b',
        closed: '#64748b',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        'label-md': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'data-display': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'headline-lg': ['Inter', 'ui-sans-serif', 'sans-serif'],
        'headline-md': ['Inter', 'ui-sans-serif', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'data-display': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
      spacing: {
        'container-margin': '1rem',
        'section-padding': '1.5rem',
        'inline-gap': '0.5rem',
        'stack-gap': '0.75rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      boxShadow: {
        float: '0px 4px 12px rgba(10, 25, 47, 0.05)',
        '2xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      },
    },
  },
  plugins: [],
}
