-- up
ALTER TABLE products ADD COLUMN screen_type TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN max_resolution TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN refresh_rate TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN item_condition TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN feat_curved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_includes_box INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_displayport INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_hdr INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_widescreen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_includes_cables INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_audio INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_hdmi INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN feat_ultrawide INTEGER NOT NULL DEFAULT 0;

-- down
-- SQLite: columns left in place
